# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Docker build
        run: docker build -t todo-list-app .

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} | docker login
          docker push todo-list-app